symfony_module_demo:
  path: symfonymodule/demo
  methods: [GET]
  defaults:
    _controller: 'SymfonyModule\Controller\DemoController::demoAction'
youtube_create:
  path: youtuber/create
  methods: [GET, POST]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::createAction'
youtube_list:
  path: youtuber/list
  methods: [GET]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::listAction'
youtube_delete:
  path: youtuber/delete/{id}
  methods: [GET]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::deleteAction'
youtube_update:
  path: youtuber/update/{id}
  methods: [GET, POST]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::updateAction'