symfony_module_demo:
  path: symfonymodule/demo
  methods: [GET]
  defaults:
    _controller: 'SymfonyModule\Controller\DemoController::demoAction'
youtube_create:
  path: youtuber/create
  methods: [GET, POST]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::createAction'
