symfonymodule_youtube_create:
  path: symfonymodule/youtube/create
  methods: [GET, POST]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::createAction'
symfonymodule_youtube_list:
  path: symfonymodule/youtube/list
  methods: [GET]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::listAction'
symfonymodule_youtube_delete:
  path: symfonymodule/youtube/delete/{id}
  methods: [GET]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::deleteAction'
symfonymodule_youtube_update:
  path: symfonymodule/youtube/update/{id}
  methods: [GET, POST]
  defaults:
    _controller: 'SymfonyModule\Controller\YoutubeController::updateAction'